### ISSUE TITLE
Science Engineering Library is in Noco

### ISSUE THREAD

**Issue by jzf2101** [adicu/wireless_data_processor#4]
Not Mudd

Could we update this for all our historical data and for the new data as it comes in?

**Comment by natebrennand** [comment]
So do you guys want it to be called "NoCo" or "Northwest Corner Building"?

I will fully update the pipeline, prod database, and dump file

**Comment by jzf2101** [comment]
"Northwest Corner Building" is the official name - we should probably use that one?

**Comment by jzf2101** [comment]
Thanks!

**Comment by natebrennand** [comment]
heads up, this is not yet launched
